### ISSUE TITLE
Doesn't work with eslint 6.1.0

### ISSUE THREAD

**Issue by JustFly1984** [zertosh/eslint-plugin-dependencies#22]
I have an error:

```
Failed to load plugin 'dependencies' declared in '.eslintrc.js': Cannot find module './util/traverser'
```

**Comment by gabegorelick** [comment]
Duplicate of https://github.com/zertosh/eslint-plugin-dependencies/issues/20
